### ISSUE TITLE
When use as button widget don't hide after click on save (version 1.4.3+)

### ISSUE THREAD

**Issue by vjik** [Simonwep/pickr#181] opened 2019-12-03 12:14 UTC
Code:
```
Pickr.create({
                el: D.$button.get(0), // this is my button
                theme: 'nano',
                useAsButton: true,
                default: D.$input.val() == '' ? '#ff0000' : D.$input.val(), // this is my value
                components: {
                    preview: true,
                    opacity: false,
                    hue: true,
                    interaction: {
                        input: true,
                        clear: true,
                        save: true,
                    },
                },
                strings: {
                    save: 'Сохранить',
                    clear: 'Очистить',
                },
            });
```

Problem appeared after update to version 1.4.3 and has in last release.

**Comment by Simonwep** [comment] 2019-12-03 16:09
That the widget gets closed after you press save is part of `useAsButton: false`.
If you specify a custom-button (which don't even need to be a button) you need to take care of that yourself :)

If this **has** worked in the past it'd be a "bug" since If the user wants to customize smth pickr shouldn't bother your implementation / customization.

**Comment by vjik** [comment] 2019-12-03 17:02
I set `useAsButton: true`.  

Save - this is not custom button.

When I click on "Cancel" widget closes.
When I click on "Save" widget not closes.

**Comment by Simonwep** [comment] 2019-12-03 17:48
Oh sorry, I misunderstood your case. Could you please provide a JSFiddle and not remove the Issue-template?

**Comment by Simonwep** [comment] 2019-12-03 17:54
... and closing it was never an intended behavior (see discussion #118).  If you want to close it after pressing save use the `save` event + `pickr.hide()`

**Closed by Simonwep** 2019-12-03 17:54 UTC
Labels: question

**Comment by vjik** [comment] 2019-12-03 18:00
I understand logic.

"save event + pickr.hide()" — Now I did :)

Please when you disable close widget on click on cancel - write about this in release notes.  This will allow me to remember to modify my code.

**Comment by Simonwep** [comment] 2019-12-03 18:02
@vjik I'll do!
