### ISSUE TITLE
Gradient color

### ISSUE THREAD

**Issue by WaedKhoder** [Simonwep/pickr#296] opened 2021-08-25 08:51 UTC
How to set a gradient color in pickr?

**Comment by Simonwep** [comment] 2021-09-05 08:28
Duplicate of #220 #119

**Closed by Simonwep** 2021-09-05 08:28 UTC
Labels: question

**Comment by Simonwep** [comment] 2021-09-05 08:29
I made a demo a few years ago ([gpickr](https://github.com/Simonwep/gpickr)) - but this library is feature-frozen and I'll not add anything new (see README).
