### ISSUE TITLE
Need a copy button, if there's already one then please tell me how to apply it

### ISSUE THREAD

**Issue by Keshav2567** [Simonwep/pickr#285] opened 2021-06-15 14:29 UTC
#### Your environment:
```
Version (see Pickr.version):
Used bundle (es5 or normal one):
Used theme (default is classic): 
Browser-version:  
Operating-system:  
```

**Comment by Simonwep** [comment] 2021-06-15 17:42
Duplicate of #129

**Closed by Simonwep** 2021-06-15 17:42 UTC
