### ISSUE TITLE
Allow to enter color name in color input field

### ISSUE THREAD

**Issue by bjarnef** [Simonwep/pickr#134] opened 2019-08-08 12:33 UTC
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
When enter a color name like `red` or `green` in input field no matter of the current selected mode, it seems to shortly convert to the hexa code for `red`, but then revert to orginal selected color hexa code. In the preview the round circle has however been updated.

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).
https://jsfiddle.net/Simonwep/qx2Lod6r/
Can be reproduced in the default template or the demo page.
https://simonwep.github.io/pickr/

#### What is the expected behavior?
By enter e.g. `red` it is great if change to the hexa color code for red and update the preview as well. However it shouldn't revert back to original selected color code.
It also seems it is flickering a bit when just deleting part of the hexa code.

#### Your environment:
```
Version (see Pickr.version): 1.2.6
Used bundle (es5 or normal one): Normal
Used theme (default is classic): Classic
Browser-version:  Google Chrome Version 76.0.3809.100
Operating-system:  Windows 10
```

![2019-08-08_14-32-49](https://user-images.githubusercontent.com/2919859/62703488-ab104700-b9e9-11e9-8ad9-b012903271eb.gif)

Off topic: There is a minor typoe here https://github.com/Simonwep/pickr#the-hsvacolor-object should be "Converts the object to a cmyk array" instead of "Converts the object to a cymk array".

**Comment by Simonwep** [comment] 2019-08-08 13:23
_Kinda_ a duplicate of #133, anyway fixed in 973f3174cc43c97bd437f79d1767aaeb962207a2 :) It will now convert the color-name to the current representation if the input field get's blurred!

**Closed by Simonwep** 2019-08-08 13:23 UTC
Labels: duplicate
