### ISSUE TITLE
plan to use multiple color picker

### ISSUE THREAD

**Issue by venkateshr8849** [Simonwep/pickr#161] opened 2019-10-09 13:15 UTC
i wanna to add multiple color picker in my page.i need to know how to change color based on element instead of variable

ex:  $("#picker").colorpicker("setValue", "#ffffff");

**Comment by Simonwep** [comment] 2019-10-09 13:16
Duplicate of #159, #127, #57 and #30

**Closed by Simonwep** 2019-10-09 13:16 UTC

**Comment by venkateshr8849** [comment] 2019-10-09 13:31
hey how can i set color in the element??

**Comment by Simonwep** [comment] 2019-10-09 13:38
Checkout the [FAQ](https://github.com/Simonwep/pickr#faq). No it's not possible by classname (as already asked here like 5 times). Please search for existing issues which already cover your problem and leave comment there.
