### ISSUE TITLE
Programmatically change swatches with JS

### ISSUE THREAD

**Issue by justingolden21** [Simonwep/pickr#266] opened 2021-02-25 01:38 UTC
Hi, I'm aware this isn't being maintained for new features much and is mostly just getting bug fixes.

That being said, I feel like I could at least write down my idea here in case anyone wants to try their hand (or in case there is a way to do it I didn't see in the docs)

I think the ability to change the swatches with JS would be useful. For my use case, I would just be setting them to the most recent colors, but perhaps they could favorite/save colors.

Obviously as a color picker in a simple form or setting where you're just choosing one color for one purpose, this feature doesn't have much use, but in a dedicated color / palette application this could be very useful, and having the ability to control it programmatically would enable complete freedom from the programmer's point of view.

**Comment by Simonwep** [comment] 2021-02-25 19:28
Duplicate of #70?

**Comment by Simonwep** [comment] 2021-11-06 08:29
Closing because of inactivity.

**Closed by Simonwep** 2021-11-06 08:29 UTC
Labels: question
