### ISSUE TITLE
Dinamically add input pickers and instantiate each by class, no by ID

### ISSUE THREAD

**Issue by itajackass** [Simonwep/pickr#159] opened 2019-10-01 10:32 UTC
### Do you want to request a **feature** or report a **bug**? 
feature?

#### What is the current behavior?

In a form where I can add dinamically multiple input fields for the pickers, i don't know how to instantiate each of it. It work only for first. I can't use ID, only classes.

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

https://jsfiddle.net/dvx79gz1/2/

#### What is the expected behavior?

I'd like to instantiate in a simple way multiple inputs by class only. no ID.

**Comment by Simonwep** [comment] 2019-10-01 11:28
Duplicate of #127, #57 and #30

**Closed by Simonwep** 2019-10-01 11:28 UTC

**Comment by itajackass** [comment] 2019-10-01 12:19
no fiddle (working) found about my question.

Tried loop method without success (updated fiddle): https://jsfiddle.net/dvx79gz1/12/

**Comment by Simonwep** [comment] 2019-10-09 13:25
Checkout [how to use it with input-elements](https://github.com/Simonwep/pickr/wiki/Using-Pickr-in-an-HTML-Form). And this [example](https://jsfiddle.net/Simonwep/0uzk3o7g/5/) of how to do it.
I'll add this as an example to the README since a lot of people struggle with it.
