### ISSUE TITLE
When default color = null - color picker should work as expected

### ISSUE THREAD

**Issue by knagode** [Simonwep/pickr#222] opened 2020-06-16 13:07 UTC
#### What is the current behavior?

If `null` is set as default color, color picker shows transparent color in selector

![Screenshot 2020-06-16 15 00 57](https://user-images.githubusercontent.com/4473199/84777892-76debd00-afe2-11ea-926f-075e679dc6be.png)

### JSFiddle

https://jsfiddle.net/p4hzr8k3/

#### What is the expected behaviour?
![Screenshot 2020-06-16 15 04 07](https://user-images.githubusercontent.com/4473199/84778003-a261a780-afe2-11ea-9763-139c2f39a863.png)

**Comment by Simonwep** [comment] 2020-06-16 13:28
I believe this is a duplicate of #178, You have to set a default color and manually clear it as pickr shouldn't automatically position all elements to black as in your second screenshot. The default-color is required to initialize the UI :)

**Closed** 2020-06-19 13:30 UTC
Labels: duplicate
