### ISSUE TITLE
Multiple instences on single page

### ISSUE THREAD

**Issue by MuhammadSaim** [Simonwep/pickr#221] opened 2020-06-13 07:00 UTC
#### Your environment:
```
Version (see Pickr.version): 1.7.0
Used bundle (es5 or normal one): es5
Used theme (default is classic): Nano
Browser-version:  Chrome Version 83.0.4103.97 (Official Build) (64-bit)
Operating-system:  Windows 10
```
I'm using this on single page I have 5 positions to add this color picker on the page but its working fine on the first position  but other four pickers is not displaying I think picker is just pic first find elements with class name and render it

javascript

```javascript
    const pickr_fg = Pickr.create({
        el: '.fg-color-picker',
        theme: 'nano', // or 'monolith', or 'nano'
        lockOpacity: true,
        defaultRepresentation: 'RGBA',
        swatches: null,
        default: "#2d3436",
        components: {
            // Main components
            preview: true,
            opacity: true,
            hue: true,
            // Input / output Options
            interaction: {
                save: true,
                clear: true,
                input: true
            }
        }
    });
```

HTML

```html
<div class="ml-3">
<div class="fg-color-picker"></div>                                                
</div>
```

I have this div with the class 5 times on my single page but its render 1st one.

![image](https://user-images.githubusercontent.com/19898499/84562361-6bcf2700-ad6d-11ea-880b-d938e6459be1.png)
![image](https://user-images.githubusercontent.com/19898499/84562376-80abba80-ad6d-11ea-8390-03f712142b11.png)

**Comment by Simonwep** [comment] 2020-06-13 08:42
Duplicate of #218, #159, #161, #127,  #194, #57, #30.... Seriously, please check if your questions has been asked before

**Closed by Simonwep** 2020-06-13 08:42 UTC
Labels: question

**Comment by tovutifunk** [comment] 2020-11-05 22:34
I've looked through all of the 'duplicates'. Can we crush this once and for all? Final Answer: You cannot use multiple Pickr's on the same page. That's the answer, right?
